xManik/Controllers/ServicesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using xManik.EF;
using xManik.Managers;
using xManik.Models;
using xManik.Repositories;

namespace xManik.Controllers
{
    public class ServicesController : Controller
    {
        private readonly WorkContext _context;
        private readonly UserProfileManager<UserProfile> _userProfileManager;
        private readonly ServicesManager<Service> _servicesManager;

        public ServicesController(ApplicationDbContext context)
        {
            _context = new WorkContext(context);
            _userProfileManager = new UserProfileManager<UserProfile>(_context);
            _servicesManager = new ServicesManager<Service>(_context);
        }

        // GET: Services
        public IActionResult Index()
        {
            return View(_context.Services.GetAll());
        }

        [Authorize(Roles = "Provider")]
        public IActionResult UserServices()
        {
            return View(_userProfileManager.GetAllServices(User));
        }

        // GET: Services/Details/5
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = _servicesManager.Find(id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // GET: Services/Create
        [Authorize(Roles = "Provider")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Services/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Provider")]
        public async Task<IActionResult> Create([Bind("Id,UserProfileId,Description,Price,Duration,DatePublished,IsPromoted")] Service service)
        {
            if (ModelState.IsValid)
            {
                service.UserProfileId = _userProfileManager.GetUserProfileId(User);
                await _servicesManager.CreateAsync(service);

                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        // GET: Services/Edit/5
        [Authorize(Roles = "Provider")]
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = _servicesManager.Find(id);
            if (service == null)
            {
                return NotFound();
            }
            return View(service);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Provider")]
        public async Task<IActionResult> Edit(string id, [Bind("Id,UserProfileId,Description,Price,Duration,DatePublished,IsPromoted")] Service service)
        {
            if (id != service.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _servicesManager.UpdateAsync(service);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_servicesManager.IsServiceExists(service.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        // GET: Services/Delete/5
        [Authorize(Roles = "Provider")]
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = _servicesManager.Find(id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Provider")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var service = _servicesManager.Find(id);
            await _servicesManager.RemoveAsync(service);

            return RedirectToAction(nameof(Index));
        }
    }
}

xManik/Views/Services/AllServices.cshtml
@model xManik.Extensions.PaginatedList<Service>

@{
    ViewData["Title"] = "Index";
}

    <h2>Services</h2>

    <div class="row">
        <div class="col-sm-3">
            <!--left col-->
            <ul class="list-group">
                <li class="list-group-item text-muted" contenteditable="false">Filters</li>
                <li class="list-group-item text-center">
                    <a asp-action="AllServices" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">@Html.DisplayNameFor(model => model.FirstOrDefault().Price)</a>
                </li>
                <li class="list-group-item text-center">
                    <a asp-action="AllServices" asp-route-sortOrder="@ViewData["RateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">@Html.DisplayNameFor(model => model.FirstOrDefault().Provider.Rate)</a>
                </li>
                <li class="list-group-item text-center">
                    <a asp-action="AllServices" asp-route-sortOrder="@ViewData["DurationSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">@Html.DisplayNameFor(model => model.FirstOrDefault().Duration)</a>
                </li>
                <li class="list-group-item text-center">
                    <a asp-action="AllServices" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">@Html.DisplayNameFor(model => model.FirstOrDefault().DatePublished)</a>
                </li>
                <li class="list-group-item text-center">
                    <form asp-action="AllServices" method="get">
                        <div class="form-group">
                            <label for="inputdefault">Find by description</label>
                            <input type="text" class="form-control" name="SearchString" value="@ViewData["currentFilter"]" />
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Search" class="btn btn-default" /> |
                            <a asp-action="AllServices">Back to Full List</a>
                        </div>
                    </form>
                </li>
            </ul>
        </div>

        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
            @if (Model.Count == 0)
            {
                <h1>Sorry, no services with that description:</h1>
                <h2><i>@ViewData["CurrentFilter"]</i></h2>
            }
            @foreach (var item in Model)
            {
                <div class="well well-sm card"
                     @if (item.IsPromoted) { @: style="background-color: #B39DDB"
                                      }>

                    <a asp-action="Information" asp-route-id="@item.Id">More Details</a>
                    <div class="card-body">
                        <h3 class="card-title">Product Name</h3>
                        <h4>$@item.Price</h4>
                        <h4>@item.Provider.Rate</h4>
                        <h4>@item.Duration</h4>
                        <h4>@item.DatePublished</h4>
                        @if (item.IsPromoted)
                        {
                            <h4>PROMOTED</h4>
                        }

                        <p class="card-text">@item.Description Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente dicta fugit fugiat hic aliquam itaque facere, soluta. Totam id dolores, sint aperiam sequi pariatur praesentium animi perspiciatis molestias iure, ducimus!</p>
                    </div>
                    @if (User.IsInRole("Client"))
                {
                        @Html.ActionLink("Замовити", "Order", "Services", new { serviceId = item.Id }, null);
                }
                </div>
            }
        </div>
    </div>
    <br /><br />
    <div class="center-block text-center">
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }

        <a asp-action="AllServices"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-page="@(Model.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @prevDisabled">
            Previous
        </a>
        <a asp-action="AllServices"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-page="@(Model.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @nextDisabled">
            Next
        </a>
    </div>

xManik/Views/Services/DefaultEmptyPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<h2 class="text-center">Be first and publish yout services!</h2>

xManik/Views/Services/Information.cshtml
@model Service

@{
    ViewData["Title"] = "Information";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Information</h2>

<div>
    <h4>Service</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DatePublished)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DatePublished)
        </dd>
    </dl>
</div>

xManik/Views/Services/Order.cshtml
@model RegisterOrderViewModel
@{
    ViewData["Title"] = "MakeOrder";
}

<h2>MakeOrder</h2>

<div class="row">
    <div class="col-md-4">
        <form  method="post">
            <div class="form-group">
                <label asp-for="ServiceTime"></label>
                <input asp-for="ServiceTime" class="form-control" />
                <span asp-validation-for="ServiceTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDetails"></label>
                <input asp-for="OrderDetails" class="form-control" />
                <span asp-validation-for="OrderDetails" class="text-danger"></span>
            </div>
            <input asp-for="ServiceId" value="@ViewBag.ServiceId" class="form-control hidden" />
            <input asp-for="UserId" value="@ViewBag.UserId" class="form-control hidden" />
            <button type="submit" class="btn btn-default">Замовити</button>
        </form>
        @ViewBag.token
    </div>
</div>