xManik/Controllers/ReviewsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using xManik.Data;
using xManik.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace xManik.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReviewsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Reviews
        public IActionResult Index(string id)
        {
            var provider = _context.Providers.Include(p => p.Reviews).Where(p => p.Id == id).FirstOrDefault();
            if (provider == null)
            {
                throw new ApplicationException();
            }
            return PartialView(Tuple.Create(provider.Reviews, id));

        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Client")]
        public async Task<IActionResult> Create([FromBody]dynamic data)
        {
            var clientId = (string)data["ClientId"];

            if (clientId == null || clientId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                throw new ApplicationException("Invalid user");
            }
            var providerId = (string)data["ProviderId"];
            var review = new Review()
            {
                DatePosted = DateTime.Now,
                Message = data["Message"],
                Rating = data["Rating"],
                ClientId = clientId
            };
            var provider = await _context.Providers.Include(p => p.Reviews).Where(p => p.Id == providerId).FirstOrDefaultAsync();
            if (provider == null)
            {
                throw new ApplicationException("Cannot add review for this provider");
            }
            provider.Reviews.Add(review);
            provider.Rate = RecalculateRate(provider);
            await _context.SaveChangesAsync();
            return Ok();
        }

        private double RecalculateRate(Provider provider)
        {
            int reviewsAmount = provider.Reviews.Count;
            double newRate = 0;
            if (reviewsAmount != 0)
            {
                newRate = provider.Reviews.Sum(p => p.Rating) * 1.0 / (reviewsAmount);
            }
            return newRate;
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ReviewId,DatePosted,Message")] Review review)
        {
            if (id != review.ReviewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.ReviewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Client")]
        public async Task<IActionResult> DeleteConfirmed([FromBody]string id)
        {
            var review = await _context.Reviews.Include(p => p.Provider).SingleOrDefaultAsync(m => m.ReviewId == id);
            if (review.ClientId != User.FindFirstValue(ClaimTypes.NameIdentifier) || review.Provider == null || review == null)
            {
                throw new ApplicationException("invalid id");
            }
            var providerId = review.Provider.Id;
            _context.Reviews.Remove(review);
            await _context.SaveChangesAsync();
            var provider = await _context.Providers.Include(p => p.Reviews).Where(p => p.Id == providerId).FirstOrDefaultAsync();
            provider.Rate = RecalculateRate(provider);
            await _context.SaveChangesAsync();
            return Ok();
        }

        private bool ReviewExists(string id)
        {
            return _context.Reviews.Any(e => e.ReviewId == id);
        }
    }
}

xManik/Views/Reviews/Create.cshtml
@model xManik.Models.Review

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Review</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DatePosted" class="control-label"></label>
                <input asp-for="DatePosted" class="form-control" />
                <span asp-validation-for="DatePosted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

xManik/Views/Reviews/Edit.cshtml
@model xManik.Models.Review

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Review</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReviewId" />
            <div class="form-group">
                <label asp-for="DatePosted" class="control-label"></label>
                <input asp-for="DatePosted" class="form-control" />
                <span asp-validation-for="DatePosted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

xManik/Views/Reviews/Index.cshtml
@model Tuple< ICollection<xManik.Models.Review> , string>
@using System.Security.Claims;
@{
    ViewData["Title"] = "Index";
    var currentClientId = User.FindFirstValue(ClaimTypes.NameIdentifier);
}

<div ng-app="myApp" class="section sm-padding bg-grey">
    @if (User.IsInRole("Client"))
    {
        <div class="col-md-12">
            <form class="form-horizontal" ng-controller="AddReviewCtrl">
                <h3 class="text-center">Add your review about this user</h3>
                <br/>
                <div class="form-group">
                    <label class="col-md-2 control-label" for="message">Your message</label>
                    <div class="col-md-9">
                        <textarea class="form-control" ng-model="review.Message" name="message" placeholder="Please enter your feedback here..." rows="5"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" for="message">Your rating</label>
                    <div class="col-md-9">
                        <input id="input-21e" value="0" type="number" ng-model="review.Rating" class="rating" min=0 max=5 step=0.5 data-size="xs">
                    </div>
                </div>
                <button type="button" ng-click="add(review,'@currentClientId','@Model.Item2','@Url.Action("Create","Reviews")')" class="btn btn-info center-block">Add</button>
            </form>
        </div>
        <hr>
    }


    <div class="blog-comments">
        <h3 class="title">(@Model.Item1.Count) Reviews</h3>
        @foreach (var review in Model.Item1)
        {
        <!-- comment -->
            <div class="media bg-light-aqua" ng-controller="DeleteReviewCtrl">
                <div class="media-left">
                    <img class="media-object" src="./img/perso2.jpg" alt="">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">
                        @review.ClientId<span class="time">@review.DatePosted</span>
                        @if (review.ClientId == currentClientId)
                        {
                            <a class="reply" ng-click="delete('@review.ReviewId','@Url.Action("Delete", "Reviews")')">Delete</a>
                        }
                    </h4>
                    <p>@review.Message</p>
                </div>
                <div class="review-block-rate">
                    <div class="col-sm-12">
                        <input disabled value="@review.Rating.ToString().Replace(',','.')" type="number" class="rating" step="0.5" data-size="xs">
                    </div>
                </div>
            </div>
            <br />
             <!-- /comment -->
        }
    </div>
</div>