xBlogger/Controllers/ChanelController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using xBlogger.EF;
using xBlogger.Managers;
using xBlogger.Models;
using xBlogger.Repositories;

namespace xBlogger.Controllers
{
    public class ChanelController : Controller
    {
        private readonly WorkContext _context;
        private readonly UserProfileManager<UserProfile> _userProfileManager;
        private readonly ChanelsManager<Chanel> _chanelsManager;

        public ChanelController(ApplicationDbContext context)
        {
            _context = new WorkContext(context);
            _userProfileManager = new UserProfileManager<UserProfile>(_context);
            _chanelsManager = new ChanelsManager<Chanel>(_context);
       }

        public IActionResult Index()
        {
            return View(_chanelsManager.GetAll());
        }

        [Authorize(Roles = "Blogger")]
        public IActionResult UserChanels()
        {
            return View(_userProfileManager.GetAllChanels(User));
        }

        // GET: Chanels/Details/5
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chanel = _chanelsManager.Find(id);
            if (chanel == null)
            {
                return NotFound();
            }

            return View(chanel);
        }
               
        // GET: Chanels/Create
        [Authorize(Roles = "Blogger")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Chanels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Blogger")]
        public async Task<IActionResult> Create([Bind("Network,Category,Description")] Chanel chanel)
        {
            if (ModelState.IsValid)
            {
                chanel.UserProfileId = _userProfileManager.GetUserProfileId(User);
                await _chanelsManager.CreateAsync(chanel);
                await _chanelsManager.ConfirmChanel(chanel);

                return RedirectToAction(nameof(Index));
            }
            return View(chanel);
        }

        // GET: Chanels/Edit/5
        [Authorize(Roles = "Blogger")]
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chanel = _chanelsManager.Find(id);
            if (chanel == null || !_userProfileManager.IsUserHasChanel(User,chanel))
            {
                return NotFound();
            }
            return View(chanel);
        }

        // POST: Chanels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Blogger")]
        public async Task<IActionResult> Edit(string id, [Bind("ChanelId,UserProfileId,Network,Category,Description")] Chanel chanel)
        {
            if (id != chanel.ChanelId || !_userProfileManager.IsUserHasChanel(User, chanel))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _chanelsManager.UpdateAsync(chanel);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_chanelsManager.IsChanelExists(chanel.ChanelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(chanel);
        }

        // GET: Chanels/Delete/5
        [Authorize(Roles = "Blogger")]
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chanel = _chanelsManager.Find(id);
            if (chanel == null || !_userProfileManager.IsUserHasChanel(User, chanel))
            {
                return NotFound();
            }

            return View(chanel);
        }

        // POST: Chanels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Blogger")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var chanel = _chanelsManager.Find(id);
            if(chanel == null || !_userProfileManager.IsUserHasChanel(User, chanel))
            {
                return NotFound();
            }
            await _chanelsManager.RemoveAsync(chanel);
            return RedirectToAction(nameof(Index));
        }
    }
}

xBlogger/Controllers/DealController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using xBlogger.EF;
using xBlogger.Managers;
using xBlogger.Models;
using xBlogger.Repositories;

namespace xBlogger.Controllers
{
    [Authorize]
    public class DealController : Controller
    {
        private readonly WorkContext _context;
        private readonly UserProfileManager<UserProfile> _userProfileManager;
        private readonly DealsManager<Deal> _dealsManager;

        public DealController(ApplicationDbContext context)
        {
            _context = new WorkContext(context);
            _userProfileManager = new UserProfileManager<UserProfile>(_context);
            _dealsManager = new DealsManager<Deal>(_context);
        }
        
        public IActionResult AllDeals()
        {
            var userId = _userProfileManager.GetUserProfileId(User);
            var userDeals = _dealsManager.GetUserDeals(userId);

            return View(userDeals);
        }

        public async Task<IActionResult> AddDeal(string id, string role)
        {
            if (id == null)
            {
                NotFound();
            }
            var userId = _userProfileManager.GetUserProfileId(User);

            Deal deal = null;

            switch(role)
            {
                case "Blogger":
                    var assigment = _context.Assigments.Find(id);
                    if (assigment == null)
                    {
                        NotFound();
                    }
                    deal = new Deal
                    {
                        AssigmentId = id,
                        SenderId = userId,
                        RecipientId = assigment.UserProfileId
                    };
                    break;
                case "Client":
                    var chanel = _context.Chanels.Find(id);
                    if (chanel == null)
                    {
                        NotFound();
                    }
                    deal = new Deal
                    {
                        ChanelId = id,
                        SenderId = userId,
                        RecipientId = chanel.UserProfileId
                    };
                    break;
                default:
                    throw new Exception("Unknown role");
            }

            await _dealsManager.AddDealAsync(deal);

            return View();
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                NotFound();
            }

            var deal = _context.Deals.SingleOrDefault(o => o.DealId == id);
            if (deal == null)
            {
                NotFound();
            }

            deal.IsRead = true;
            _context.Deals.Update(deal);
            await _context.SaveAsync();
            return View(deal);
        }

        public async Task<IActionResult> ConfirmDeal(string id)
        {
            if (id == null)
            {
                NotFound();
            }

            var deal = _context.Deals.SingleOrDefault(o => o.DealId == id);
            if (deal == null)
            {
                NotFound();
            }

            deal.IsConfirmed = true;
            _context.Deals.Update(deal);
            await _context.SaveAsync();

            return View();
        }

        public async Task<IActionResult> DeclineDeal(string id)
        {
            if (id == null)
            {
                NotFound();
            }

            var deal = _context.Deals.SingleOrDefault(o => o.DealId == id);
            if (deal == null)
            {
                NotFound();
            }

            deal.IsConfirmed = false;
            _context.Deals.Update(deal);
            await _context.SaveAsync();

            return View();
        }
    }
}

xBlogger/Controllers/NewsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using xBlogger.EF;
using xBlogger.Extensions;
using xBlogger.Managers;
using xBlogger.Models;
using xBlogger.Repositories;

namespace xBlogger.Controllers
{
    public class NewsController : Controller
    {
        private readonly WorkContext _context;
        private readonly NewsManager _newsManager;
        private readonly IHostingEnvironment _environment;

        public NewsController(ApplicationDbContext context,
             IHostingEnvironment environment)
        {
            _context = new WorkContext(context);
            _newsManager = new NewsManager(_context);
            _environment = environment;
        }

        // GET: News
        public IActionResult AllNews(int? page)
        {
            int pageSize = 4;
            return View(PaginatedList<News>.Create(_newsManager.GetAll().AsQueryable(), page ?? 1, pageSize));
        }

        // GET: News/Details/5
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = _newsManager.Find(id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // GET: News/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Title,Text")] News news, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                await _newsManager.CreateAsync(news, file, _environment.WebRootPath);
                return RedirectToAction(nameof(AllNews));
            }
            return View(news);
        }

        // GET: News/Edit/5
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = _newsManager.Find(id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Title,Text,Image,DatePublished")] News news)
        {
            if (id != news.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _newsManager.UpdateAsync(news);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsExists(news.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(AllNews));
            }
            return View(news);
        }

        // GET: News/Delete/5
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = _newsManager.Find(id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await _newsManager.RemoveAsync(id, _environment.WebRootPath);
            return RedirectToAction(nameof(AllNews));
        }

        private bool NewsExists(string id)
        {
            return _context.News.Any(e => e.Id == id);
        }
    }
}

xBlogger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - xBlogger</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/navbar-fixed-side.css" />
        <link rel="stylesheet" href="~/lib/Font-Awesome/web-fonts-with-css/css/fontawesome-all.min.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/navbar-fixed-side.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
              asp-fallback-href="~/lib/Font-Awesome/web-fonts-with-css/css/fontawesome-all.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    @if (User.Identity.IsAuthenticated)
    {
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-3 col-lg-2" style="padding:0px;margin:0px;">
                    <nav class="navbar navbar-default navbar-fixed-side" style="background-color:#362e4c;padding-left:10px;" >
                        @await Html.PartialAsync("_UserProfileMenuPartial.cshtml")
                    </nav>
                </div>
                <div class="col-sm-9 col-md-9 col-lg-10">
                    <div class="body-content">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <nav id="header" class="navbar navbar-default navbar-fixed-top">
            <div id="header-container" class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a id="brand" asp-area="" asp-controller="Home" asp-action="Main" class="navbar-brand">xBlogger</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Main">Home</a></li>
                        <li><a asp-area="" asp-controller="News" asp-action="AllNews">News</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
        <div id="content-block" class="container body-content content-padding-md">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - xBlogger</p>
            </footer>
        </div>
    }

    @RenderSection("Scripts", required: false)
</body>
</html>

xBlogger/Views/Shared/_UserProfileMenuPartial.cshtml
@using xBlogger.Extensions.IdentityExtensions

<div class="navbar navbar-default navbar-left">
    <div class="profile-sidebar">
        <div class="profile-usertitle">
            <div class="profile-usertitle-name">
                <p class="small white-text">
                    @User.GetUserName()
                </p>
            </div>
            <h4 class="gold-text ">   @User.GetUserRole() </h4>
        </div>

        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right xs-padding">
            <ul class="nav nav-pills nav-stacked left-side-nav">
                <li class="@UserProfileMenuNavPages.MainNavClass(ViewContext)"><a asp-controller="Home" asp-action="Main"><i class="fa fa-home" style="font-size:18px;color:white"></i> Home</a></li>
                <li class="@UserProfileMenuNavPages.AllAssigmentsNavClass(ViewContext)"><a asp-controller="Assigment" asp-action="AllAssigments"><i class="fa fa-book" style="font-size:18px;color:white"></i> Assigments</a></li>
                <li class="@UserProfileMenuNavPages.NewsNavClass(ViewContext)"><a asp-controller="News" asp-action="AllNews"><i class="fa fa-news" style="font-size:18px;color:white"></i> News</a></li>
                <li class="@UserProfileMenuNavPages.ManageAccountNavClass(ViewContext)"><a asp-controller="Manage" asp-action="Index"><i class="fa fa-cog fa-spin" style="font-size:18px;color:white"></i> Manage account</a></li>

                @if (User.IsInRole("Client") || User.IsInRole("Blogger"))
                {
                    <li class="@UserProfileMenuNavPages.UserProfileNavClass(ViewContext)"><a asp-controller="UserProfile" asp-action="ManageUserProfile"><i class="fa fa-universal-access" style="font-size:18px;color:white"></i> Manage User profile</a></li>
                    <li class="@UserProfileMenuNavPages.UserDealsNavClass(ViewContext)"><a asp-controller="Deal" asp-action="AllDeals"><i class="fa fa-check" style="font-size:18px;color:white"></i> My deals<span style="float:right;" class="badge">@ViewData["newDeals"]</span></a></li>
                }
                @if (User.IsInRole("Client"))
                {
                    <li class="@UserProfileMenuNavPages.SearchChannelsNavClass(ViewContext)"><a asp-controller="Chanel" asp-action="Index"><i class="glyphicon glyphicon-search"></i> Search Channels</a></li>
                    <li class="@UserProfileMenuNavPages.AddAssigmentNavClass(ViewContext)"><a asp-controller="Assigment" asp-action="Create"><i class="fa fa-tasks" style="font-size:18px;color:white"></i> Add assigment</a></li>
                    <li class="@UserProfileMenuNavPages.UserAssigmentsNavClass(ViewContext)"><a asp-controller="Assigment" asp-action="UserAssigments"><i class="fa fa-safari" style="font-size:18px;color:white"></i> My assigments</a></li>
                }
                @if (User.IsInRole("Blogger"))
                {
                    <li class="@UserProfileMenuNavPages.AddAssigmentNavClass(ViewContext)"><a asp-controller="Chanel" asp-action="Create"><i class="fa fa-paper-plane" style="font-size:18px;color:white"></i> Add chanel</a></li>
                    <li class="@UserProfileMenuNavPages.UserAssigmentsNavClass(ViewContext)"><a asp-controller="Chanel" asp-action="UserChanels"><i class="fa fa-tv" style="font-size:18px;color:white"></i> My chanels</a></li>
                }
                <li><button type="submit" class="btn btn-link navbar-btn navbar-link"><i class="fa fa-outdent" style="font-size:18px;color:white"></i> Log out</button></li>
            </ul>
        </form>
    </div>
</div>